export const EMPTY_LIST = [
    { value: '', disabled: true },
    { value: '', disabled: true },
    { value: '', disabled: true },
    { value: '', disabled: true },
    { value: '', disabled: true },
    { value: '', disabled: true },
    { value: '', disabled: true },
    { value: '', disabled: true },
    { value: '', disabled: true },
    { value: '', disabled: true },
    { value: '', disabled: true },
    { value: '', disabled: true },
    { value: '', disabled: true },
    { value: '', disabled: true },
    { value: '', disabled: true },
    { value: '', disabled: true },
    { value: '', disabled: true },
    { value: '', disabled: true },
    { value: '', disabled: true },
    { value: '', disabled: true },
    { value: '', disabled: true },
    { value: '', disabled: true },
    { value: '', disabled: true },
    { value: '', disabled: true },
]