export const emptyList = [
    { value: '', disabled: true },
    { value: '', disabled: true },
    { value: '', disabled: true },
    { value: '', disabled: true },
    { value: '', disabled: true },
    { value: '', disabled: true },
    { value: '', disabled: true },
    { value: '', disabled: true },
    { value: '', disabled: true },
    { value: '', disabled: true },
    { value: '', disabled: true },
    { value: '', disabled: true },
    { value: '', disabled: true },
    { value: '', disabled: true },
    { value: '', disabled: true },
    { value: '', disabled: true },
    { value: '', disabled: true },
    { value: '', disabled: true },
    { value: '', disabled: true },
    { value: '', disabled: true },
    { value: '', disabled: true },
    { value: '', disabled: true },
    { value: '', disabled: true },
    { value: '', disabled: true },
]